### ISSUE TITLE
Throwing windows to other spaces fails on macOS 15 beta 1

### ISSUE THREAD

**Issue by FelixLisczyk** [ianyh/Amethyst#1662]
**Describe the bug**
The keyboard shortcuts to throw windows to other spaces don't work in the first beta release of macOS 15.

**Applications**
Amethyst and Safari. The problem applies to other apps as well.

**To Reproduce**
1. Launch Amethyst on macOS 15 beta.
2. Trigger a keyboard shortcut that throws the active window to another space.

**Expected behavior**
The window moves to the new space.

**Actual behavior**
The window flickers for a moment but stays in the current space.

**Versions**
 - macOS: 15.0 Beta (24A5264n)
 - Amethyst: 0.21.1 (111)
 
**Log Messages**
The following log messages appear in the Xcode 16.0 beta console (I've checked out the `development` branch):

```
14:49:28.723 💚 DEBUG ScreenManager.setNeedsReflow():177 - Screen: 99CDF38A-8253-433F-A741-B3538F7C6E6E -- Window Change: remove(window: <Amethyst.AXWindow: 0x6000005ff440> <Title: Amethyst — Amethyst.xcworkspace> <pid: 12593>)
14:49:28.723 ❤️ ERROR Window.move():388 - failed to set compat aside id: CGError(rawValue: 717863)
14:49:28.762 💚 DEBUG ScreenManager.setNeedsReflow():177 - Screen: 99CDF38A-8253-433F-A741-B3538F7C6E6E -- Window Change: add(window: <Amethyst.AXWindow: 0x6000005ff440> <Title: Amethyst — Amethyst.xcworkspace> <pid: 12593>)
14:49:28.996 💚 DEBUG ScreenManager.setNeedsReflow():177 - Screen: 99CDF38A-8253-433F-A741-B3538F7C6E6E -- Window Change: applicationActivate
```

**Comment by swibrow** [comment]
I have this issue on 14.5

**Comment by ianyh** [comment]
This was (partly) fixed in 0.21.1 for macOS 14.5, but macOS 15 might be the actual nail in the coffin for moving windows between spaces.

**Comment by mischavandenburg** [comment]
I'm having the same issue on 14.5.

Does this mean this won't be possible anymore from here on out?

**Comment by ianyh** [comment]
The mechanism by which we do it is no longer possible, it seems. Until someone figures out a different way (which may very well not be possible, particularly with SIP enabled), then we are out of luck. I don't really have the bandwidth to do that kind of diving, but I'm going to keep my eye on it to see if anything changes (on the open source end or the Apple end).

**Comment by craftWolf** [comment]
I experienced the same issue on macOS 14.5 and updated the app to 0.21.1 but that doesn't fix it for me, I can only throw the Amethyst Preferences window but not others. When I press the keyboard shortcut it just un-focuses the windows for me.

PS: Just providing some input for this issue.

**Comment by asyncopation** [comment]
Same issue on 13.6.8, same behavior as the above comment describes.

Worth noting this is an issue on other MacOS window managers as well:
https://github.com/koekeishiya/yabai/issues/2380

**Comment by cheese-melted** [comment]
I have the same problem after my recent update: 13.6.9
Window does glitch a bit before nothing happening.

**Comment by porkloin** [comment]
Just updated to Sequoia beta on one of my machines and am having the same issue.

It looks like yabai has a solution, they closed some stuff out this week? https://github.com/koekeishiya/yabai/issues/2380

It requires their "scripting addition" (AKA disabling SIP) which AFAIK isn't something amethyst has ever required. Sad to see this functionality get broken through Apple updates 😢

**Comment by FeernandoOFF** [comment]
Any updates on this one? 👀

**Comment by kolchurinvv** [comment]
15.0 is out now and throwing doesn’t work on it 😞

**Comment by ianyh** [comment]
I think AeroSpace does its own virtual space thing by showing and hiding sets of windows instead of relying on the native spaces. It's a good solution if you want the functionality, but don't want to mess with SIP. I like the native spaces for a variety of reasons, personally, though it does suck that this seems to be the end of space throwing for Amethyst for now. Maybe Apple will take their underlying window management framework and make it a public API at some point, but I'm not holding my breath.

**Comment by fvcci** [comment]
same issue with me

**Comment by jcarlos7121** [comment]
I think this is an evil intention by Apple to force users to use their inferior window management features they released with Sequoia

**Comment by ianyh** [comment]
See https://github.com/ianyh/Amethyst/discussions/1682
